import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { UserContextProvider } from "@/src/context/UserContext";
import { AuthContextProvider } from "../context/AuthContext";
import { SnackBarContextProvider } from "../context/SnackBarContext";
import { Toaster } from "react-hot-toast";
import { TaskContextProvider } from "../context/TaskContext";
import { SocketProvider } from "../context/SocketContext";
import { QuoteSchemaContextProvider } from "../context/QuoteSchemaContext";
import { RecoilProvider } from "../context/RecoilContext";

// import { RecoilRoot } from "recoil";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} style={{ backgroundColor: "white" }}>
        <div>
          <Toaster position="bottom-left" />
        </div>
        <QuoteSchemaContextProvider>
          <SnackBarContextProvider>
            <AuthContextProvider>
              <UserContextProvider>
                <TaskContextProvider>
                  <SocketProvider>
                    <RecoilProvider>{children}</RecoilProvider>
                  </SocketProvider>
                </TaskContextProvider>
              </UserContextProvider>
            </AuthContextProvider>
          </SnackBarContextProvider>
        </QuoteSchemaContextProvider>
      </body>
    </html>
  );
}
