"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { UserContextProvider } from "@/src/context/UserContext";
import { AuthContextProvider } from "../context/AuthContext";
import { SnackbarAlert } from "../components/ui/SnackbarAlert";
import { SnackBarContext } from "../context/SnackBarContext";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [snackbar, setSnackbar] = useState({
    open: false,
    message: "",
    severity: "info", // default severity
  });
  return (
    <html lang="en">
      <body className={inter.className} style={{ backgroundColor: "white" }}>
        <SnackBarContext.Provider value={{ setSnackbar }}>
          <AuthContextProvider>
            <UserContextProvider>{children}</UserContextProvider>
          </AuthContextProvider>
          <SnackbarAlert
            openSnackbarShare={snackbar.open}
            setOpenSnackbarShare={setSnackbar}
            snackbar={snackbar}
          />
        </SnackBarContext.Provider>
      </body>
    </html>
  );
}
