name: Lint Code

on:
  push:
    branches:
      - main # Replace with your target branch, or remove the `branches` filter to run on push to any branch

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18" # Specify the Node.js version you are using
          cache: "pnpm"
      - name: Install PNPM
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Run lint
        run: pnpm run lint
