name: Lint and Auto-fix

on: [push, pull_request]

jobs:
  lint-and-fix:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 6.32.9

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run lint with auto-fix
        run: pnpm run lint -- --fix

      - name: Commit and push if there were changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated lint fixes
          branch: ${{ github.head_ref }}
          file_pattern: src/**/*.ts src/**/*.tsx
